###
//COMPANY:login
POST http://localhost:8080/api/login
Content-Type: application/json

{
  "company":true,
  "userPhoneNumber": "618239",
  "userPassword": "baidu123"
}

> {% client.global.set("token", response.headers.valueOf("authorization")); %}
###
//STUDENT:login
POST http://localhost:8080/api/login
Content-Type: application/json

{
  "student":true,
  "userPhoneNumber": "13923894423",
  "userPassword": "Qrter122"
}

> {% client.global.set("token", response.headers.valueOf("authorization")); %}
###
//ADMIN:login
POST http://localhost:8080/api/login
Content-Type: application/json

{
  "admin":true,
  "userName": "systemAdmin1",
  "userPassword": "systemAdmin1"
}

> {% client.global.set("token", response.headers.valueOf("authorization")); %}
###